### ISSUE TITLE
Run:api not working for POST method

### ISSUE THREAD

**Issue by geekrishabh** [GeekyAnts/ga-wdio#8]
When I am trying to hit my POST method request, I am getting an unexpected error but the syntax for the API file is as defined in the documentation. Below I am attaching my API code.

```js
let index = {};

index.name = 'Login User';

index.uri = '/auth/login';

index.method = 'POST';

index.body = {
  email: 'private@rishabh.come',
  password: '123456'
};

index.timeout = 10 * 1000;

index.headers = {
  'Content-Type': 'application/json'
};


index.expected = {
  headers: {
    'Content-Type': 'application/json; charset=utf-8'
  },

  body: {
    data: {
      id: 'number',
      firstName: 'string',
      email: 'string',
      lastName: 'string',
      userType: 'string',
      email: 'string',
      lastLoggedIn: 'string',
      jwtToken: 'string'
    },
    success: 'boolean',
    message: 'string'
  }
};

module.exports = index;
```

And I am receiving below-mentioned node error on my CLI once the command has successfully exited.

```sh
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at helpers.buildRequest (/usr/local/lib/node_modules/ga-wdio/libraries/helpers/http/api.js:7:43)
    at Object.sync.start (/usr/local/lib/node_modules/ga-wdio/libraries/run/api/sync.js:12:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:17379) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by faizahmedfarooqui** [comment]
@GeekRishabh I have fixed the issues you've mentioned in our new release ie. v1.3.3.
